### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank_reproducibility_preprint#1]
I haven't yet added this to the README. I'm still going to need scachepy in my notebooks because I don't want to re-compute velocities and my stochastic kernel each time I have to re-generate a figure. I suggest we have a caching directory that mirrors the structure of the data directory. We won't share the actual cached files because they are too large but I will place `.gitkeep` files so that we have the same folder structure. What are your thoughts on this?

**Comment by Marius1311** [comment]
In the actual notebooks, I would handle this similarly to the tutorials and tell the user that there is something being cached here, he/she should feel free to re-compute this.

**Comment by michalk8** [comment]
Yes, I think keeping it in .gitkeep is a good idea.

**Comment by Marius1311** [comment]
I will do it like this: I will check at the beginning of the notebook if scachepy can be imported and I will set a flag `caching=True/False`. In the actual computations, I will then check the value of this flag and either import cached values or recompute.
