### ISSUE TITLE
CoC

### ISSUE THREAD

**Issue by michalk8** [theislab/cellrank_reproducibility_preprint#2]
My remarks:
 - for the paths, instead of get_paths function which return a dictionary, let's create 1 file where the paths are defined as constans - I think it will be more readable doing and that we only import paths that we need, e.g.
```python
from path import CACHE_DIR, FIG_DIR
```
- If we go for the approach above, let's also define some naming convention for these constants (e.g. directories ending with `_DIR`, data-related stuff prefixed with `DATA_`, caching with `CACHE_`, etc.)
- environment.yml or requirements.txt - I'd provide a conda environment.yaml named `cellrank-reproduciblity` with all the correct package versions (if something requires a different version, then a separate yaml file will be within that directory)
- I'd also create a small skeleton .ipynb as basis for all notebooks - this should contain e.g. importing the default packages (like scanpy/cellrank/etc), printing the versions and the sections you mention (section not needed, like `Plot results` in preprocessing notebooks will be removed when filling the notebook up)
- initials in the notebooks: it's sometimes hard for me to distinguish `ml` and `mk`, maybe if we could use different aliases or capitalize it or move it to the front before the date
- same for the dates, YYYYMMDD is not friendly format (at least for me) to read, I'd include dashes as `YYYY-MM-DD`.
- relative paths: do you mean relative to this repo's root or relative to the position of the file/notebook? I assume you mean the latter
- I'd also make 1 issue for 1 figure or their dependency and do regular PRs

**Comment by Marius1311** [comment]
Hi Mike, please link or assign me to issues, otherwise I don't get notified.

**Comment by Marius1311** [comment]
- initials: capitalize and move to the front
- data: agreed on the proposed format

**Comment by Marius1311** [comment]
todo: Update the REAMDE once we have converged on the CoC. Move it into the wiki then so we can adjust the README to be relevant to users.

**Comment by Marius1311** [comment]
Done. Usage guidelines are in the wiki now.

**Comment by michalk8** [comment]
Great, thanks @Marius1311 .
