### ISSUE TITLE
Repo size

### ISSUE THREAD

**Issue by michalk8** [theislab/cellrank_reproducibility_preprint#30]
For some reason, it's huge... Did any of us commit and data inside?
Inspecting this, it's git objects (245M	./.git/objects).
And 99M	./notebooks

I suggest we prune this once everything is done - I can do a test run on my private fork to see if we can prune the git objects.

**Comment by Marius1311** [comment]
yes, that sounds good, we can do that once we're done with everything.

**Comment by michalk8** [comment]
Can reduce it from ~346MB to ~221.

**Comment by michalk8** [comment]
@Marius1311 let me know if you want me to do this, alternatively you can do it yourself using https://rtyley.github.io/bfg-repo-cleaner/

**Comment by Marius1311** [comment]
Hi Mike, let's not do this now, we can think about such things after our release.
