### ISSUE TITLE
Scattered to do's

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank_reproducibility_preprint#31]
I'm collecting to do's from various notebooks here:
- [ ] in the main uncertainty notebook, insert links to to the stochastic MC notebook and also to the robustness notebook
- [ ] make sure supplemental gene trends are saved to the same directory. 
- [ ] remove the code of conduct again.

**Comment by michalk8** [comment]
Also,
please take a look at and update these notebooks:
- [x] https://github.com/theislab/cellrank_reproducibility/blob/main/notebooks/suppl_fig_uncertainty/ML_2020-01-10_uncertainty.ipynb
- [x] https://github.com/theislab/cellrank_reproducibility/tree/main/notebooks/fig_5_benchmarking/palantir

**Comment by Marius1311** [comment]
I cleaned both already. 

The uncertainty analysis is not just supplemental but is also a part of main figure 4, you can find it in https://github.com/theislab/cellrank_reproducibility/blob/main/notebooks/fig_4_uncertainty/ML-2020-10-17_fig_4_uncertainty.ipynb. This is the cleaned version of the notebook you posted, so I deleted the one you posted. 

For the palantir notebook, that is in the very folder you linked, cleaned up already.

**Comment by michalk8** [comment]
Great, thanks for the update!

**Comment by Marius1311** [comment]
You're welcome.

**Comment by michalk8** [comment]
I've updated uncertainty notebook with the correct links, I think this can be closed.
