### ISSUE TITLE
Fix date formatting

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank_reproducibility_preprint#33]
@michalk8 , I think your date formatting does not follow our guidelines, see https://github.com/theislab/cellrank_reproducibility/wiki/Usage-guidelines

It seems that you went for YYYY-DD-MM, whereas we agreed on YYYY-MM-DD.  Can you fix this please? Thanks!

Also in the links please...

**Comment by michalk8** [comment]
Yes, sorry, will do.

**Comment by Marius1311** [comment]
thanks!

**Comment by Marius1311** [comment]
Please don't forget to also update the table in the readme.

**Comment by michalk8** [comment]
Don't worry, I will do it once I run the memory benchmark (runtime is fine already).

**Comment by Marius1311** [comment]
great, thanks.
