### ISSUE TITLE
Prettify the table in the README a bit

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank_reproducibility_preprint#45]
The repo is public now, so we can...
- add links to nbviewer

**Comment by Marius1311** [comment]
Hi Mike, could you take care of this please? Would be important, esp. as some of the links seem to be broken atm (try the first one, gives 404)

**Comment by michalk8** [comment]
I've fixed the 1st link, others seem to be fine. Let's discuss the nbviewer tomorrow.
